# Generated by Django 3.2.9 on 2022-09-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpaymentdata',
            name='pay_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
