# Generated by Django 4.1.1 on 2022-09-12 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_userpaymentdata_pay_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpaymentdata',
            name='is_payed',
        ),
    ]
